config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'articles/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #resources are a collection of similar objects (like people and animals)
  #CRUD = Create Read Update Destroy
  #You can apply CRUD operations to items of a resource
  resources :articles
  
  root 'welcome#index'
end

#run 'rails routes' to see defined routes 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    #it's important to note that this class inherits from ApplicationRecord, which in turn inherits from ActiveRecord::Base
    #which provides basic database CRUD (Create, Read, Update and Destroy), data validation, search and ability to relate multiple models to one another
    validates :title, presence: true, length: {minimum: 5}
    #this ensures that the title must be present and a minimum of 5 characters long
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #defining a new action inside the container
  
  #it's common practice to define the index action as the very first action in a controller
  #every actions needs a view!
  def index
    @articles = Article.all
  end
  
  def show
    #find is used with the article ID - used an instance variable ('@article') to hold a reference to the article object (Rails will pass all instance variables to the view)
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  #when a form is submitted - the fields of the form are sent to Rails as parameters
  #the parameters are then referenced inside the controller actions (like the action below!) to perform a task
  #the params method is the object which represents coming in from the form.
  #the params method returns an ActionController::Parameters object, which allows you to access the keys of the hash using keys or symbols.
  def create
    #the render method is taking a hash with a key of plain and a value of 'params[:article].inspect'
    #the params method is the object which represents the parameters coming in from the form
    #this return ActionController::Parameters object - this gives access to the hash using keys or symbols (in this situation, the params from the form that matter)
    #render plain: params[:article].inspect
    
    #here we are using the new Article model to save items to the database
    #Rails models can be initialised with its respective attributes - which are automatically mapped to the respective database columns
    #Article is a reference to the class named Article (which is in models > article.rb) Class names in Ruby must start with a capital letter!
    
    #we need to prevent wrongful mass assignment, we need to allow title and text for valid use of create!
    @article = Article.new(article_params)
    
    #responsible for saving the model in the database - then we direct the user to show the action
     if @article.save
       #this tells the browser to issue another request
       redirect_to @article
     else
       #use render here instead of redirect_to so the object is passed back to the new template when it is rendered
       render 'new'
     end
  end
  
  def update
    @article = Article.find(params[:id])
    
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  #you can call destroy on Active Record objects when you want to delete them from the database.
  #no view necessary, we're redirecting to the index action
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
  
  #kept it in its own method so it can be used across multiple actions
  #made private so it can't be called outside its intended context
  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<!--form = Form Builder object-->
<!--:article is a symbol, it tells the form builder what the form is for-->
<!--this method will create two labels, two text fields and a button -->
<%= form_with model: @article, local: true do |form| %>
<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>
  
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<%= link_to 'New article', new_article_path %>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <!--we pass the named route as the second argument, then the options as another argument -->
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1>Show Articles</h1>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<p>The welcome page!</p>
<!--the link_to is a method which creates a hyperlink based on text and where to go -->
<%= link_to 'My Blog', controller: 'articles' %>